disabled_rules: # 执行时排除掉的规则
  - colon
  - comma
  - control_statement
  - identifier_name
  - type_name
  - trailing_whitespace
  - return_arrow_whitespace
  - multiple_closures_with_trailing_closure
  - nesting
  - file_length
  
line_length: 300

excluded: 
  - Pods
  - Carthage